# Generated by Django 4.0.6 on 2022-07-31 04:40

import django.core.validators
from django.db import migrations, models
import forms.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Kindly submit form with your college email only.', regex='^[2][1][a-z]{3}\\d{3}@[nith.ac.in]*')])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('branch', models.CharField(choices=[('', 'Choose Your Branch'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics And Communication Engineering', 'Electronics And Communication Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Computer Science Engineering', 'Computer Science Engineering'), ('Material Science', 'Material Science'), ('Engineering Physics', 'Engineering Physics'), ('Mathematics And Computing', 'Mathematics And Computing')], default='', max_length=100)),
                ('resume', models.FileField(upload_to='resumes/', validators=[forms.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('terms_confirmed', models.BooleanField(default=False, verbose_name='Terms & Conditions')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_heading', models.CharField(blank=True, max_length=1000, null=True)),
                ('intro_text', models.CharField(blank=True, max_length=100000000, null=True)),
                ('about_para', models.CharField(blank=True, max_length=100000000, null=True)),
                ('download_para', models.CharField(blank=True, max_length=1000000, null=True)),
                ('download_cv_pdf', models.FileField(blank=True, null=True, upload_to='sample_pdf/')),
                ('download_cv_doc', models.FileField(blank=True, null=True, upload_to='sample_doc/')),
                ('contact_para', models.CharField(blank=True, max_length=10000000, null=True)),
                ('copyright_para', models.CharField(blank=True, max_length=10000000, null=True)),
            ],
        ),
    ]
