# Generated by Django 4.0.5 on 2022-06-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rollno', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('skills', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
