# Generated by Django 4.0.6 on 2022-07-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='terms_conditions_content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='terms_conditions_title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
