# Generated by Django 4.0.8 on 2022-12-11 07:32

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import forms.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='resume',
            field=models.FileField(blank=True, default='resumes/resume.pdf', null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/lucifer/join.istenith.com/media')), upload_to='resumes/', validators=[forms.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='skills',
            field=models.CharField(max_length=200, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='strength',
            field=models.CharField(max_length=200, verbose_name='Strengths'),
        ),
    ]
