# Generated by Django 3.1.4 on 2022-06-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registerations',
            new_name='Registeration',
        ),
    ]
