# Generated by Django 4.0.6 on 2022-07-31 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_template_terms_conditions_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='insta',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='twitter',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Kindly submit form with your college email only.', regex='^[2][1][b][a-z]{2}\\d{3}@[nith.ac.in]*')]),
        ),
    ]
