# Generated by Django 4.0.5 on 2022-06-24 13:48

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20220624_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[forms.models.file_size]),
        ),
    ]
