# Generated by Django 4.0.5 on 2022-06-25 03:40

import django.core.validators
from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_registeration_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[forms.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
