# Generated by Django 4.0.5 on 2022-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_registeration_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
