# Generated by Django 4.0.6 on 2022-08-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rename_insta_template_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('s_link', models.CharField(blank=True, max_length=10000, null=True)),
                ('s_icon', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms_n_Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_conditions_title', models.CharField(blank=True, max_length=10000, null=True)),
                ('terms_conditions_content', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='template',
            name='terms_conditions_content',
        ),
        migrations.RemoveField(
            model_name='template',
            name='terms_conditions_title',
        ),
        migrations.RemoveField(
            model_name='template',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='template',
            name='whatsapp',
        ),
    ]
