# Generated by Django 4.0.5 on 2022-06-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_registeration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='branch',
            field=models.PositiveIntegerField(choices=[('Civil Engineering', 1), ('Mechanical Engineering', 2)]),
        ),
    ]
