# Generated by Django 4.0.8 on 2022-12-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_registeration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='expect_from_iste',
            field=models.TextField(blank=True, verbose_name='What do you want from ISTE?'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='skills',
            field=models.CharField(blank=True, max_length=90, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='strength',
            field=models.CharField(blank=True, max_length=90, verbose_name='Strengths'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='weakness',
            field=models.CharField(blank=True, max_length=90, verbose_name='Weakness'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='why_join_iste',
            field=models.TextField(blank=True, verbose_name='Why you want to join ISTE?'),
        ),
    ]
