# Generated by Django 4.0.6 on 2022-08-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_rename_social_links_social_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terms_n_condition',
            old_name='terms_conditions_content',
            new_name='tc_content',
        ),
        migrations.RenameField(
            model_name='terms_n_condition',
            old_name='terms_conditions_title',
            new_name='tc_title',
        ),
    ]
