# Generated by Django 4.0.8 on 2022-12-10 04:47

import django.core.validators
from django.db import migrations, models
import forms.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_registeration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='expect_from_iste',
            field=models.TextField(blank=True, null=True, verbose_name='What do you want from ISTE?'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='roll_no',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Only freshers with correct college email addresses are authorised.', regex='^[2][2][a-zA-Z]{3}\\d{3}@nith[.]ac[.]in$')], verbose_name='Roll Number'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='skills',
            field=models.CharField(max_length=90, null=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='strength',
            field=models.CharField(max_length=90, null=True, verbose_name='Strengths'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='weakness',
            field=models.CharField(max_length=90, null=True, verbose_name='Weakness'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='why_join_iste',
            field=models.TextField(null=True, verbose_name='Why you want to join ISTE?'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='branch',
            field=models.CharField(choices=[('', 'Choose Your Branch'), ('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Electronics And Communication Engineering', 'Electronics And Communication Engineering'), ('ECE Dual', 'ECE Dual'), ('Chemical Engineering', 'Chemical Engineering'), ('Computer Science Engineering', 'Computer Science Engineering'), ('CSE Dual', 'CSE Dual'), ('Material Science', 'Material Science'), ('Engineering Physics', 'Engineering Physics'), ('Mathematics And Computing', 'Mathematics And Computing')], default='', max_length=100, verbose_name='Branches'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Only freshers with correct college email addresses are authorised.', regex='^[2][2][a-zA-Z]{3}\\d{3}@nith[.]ac[.]in$')], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='resume',
            field=models.FileField(upload_to='resumes/', validators=[forms.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])], verbose_name='Resume'),
        ),
    ]
