# Generated by Django 4.0.8 on 2023-07-30 12:34

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import forms.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_alter_registeration_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/home/lucifer/join.istenith.com/media')), upload_to='resumes/', validators=[forms.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
    ]
