# Generated by Django 4.0.6 on 2022-08-07 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_rename_terms_conditions_content_terms_n_condition_tc_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terms_n_Condition',
            new_name='Terms_Condition',
        ),
    ]
