# Generated by Django 4.0.8 on 2022-12-10 11:38

import django.core.validators
from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_registeration_expect_from_iste_registeration_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[forms.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='skills',
            field=models.CharField(max_length=90, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='strength',
            field=models.CharField(max_length=90, verbose_name='Strengths'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='weakness',
            field=models.CharField(max_length=90, verbose_name='Weakness'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='why_join_iste',
            field=models.TextField(verbose_name='Why you want to join ISTE?'),
        ),
    ]
