# Generated by Django 4.0.8 on 2022-12-10 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_registeration_expect_from_iste_registeration_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='expect_from_iste',
            field=models.TextField(blank=True, verbose_name='What do you want from ISTE?'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='roll_no',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Only freshers with correct college email addresses are authorised.', regex='^[2][2][a-zA-Z]{3}\\d{3}$')], verbose_name='Roll Number'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='skills',
            field=models.CharField(max_length=90, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='strength',
            field=models.CharField(max_length=90, verbose_name='Strengths'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='weakness',
            field=models.CharField(max_length=90, verbose_name='Weakness'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='why_join_iste',
            field=models.TextField(verbose_name='Why you want to join ISTE?'),
        ),
    ]
