# Generated by Django 4.0.8 on 2022-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_registeration_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='expect_from_iste',
            field=models.TextField(null=True, verbose_name='What do you want from ISTE?'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='skills',
            field=models.CharField(blank=True, max_length=200, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='strength',
            field=models.CharField(blank=True, max_length=200, verbose_name='Strengths'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='weakness',
            field=models.CharField(max_length=200, verbose_name='Weakness'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='why_join_iste',
            field=models.TextField(null=True, verbose_name='Why you want to join ISTE?'),
        ),
    ]
