# Generated by Django 4.0.6 on 2022-08-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_rename_terms_n_condition_terms_condition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terms_Condition',
            new_name='Term_Condition',
        ),
    ]
