# Generated by Django 4.0.8 on 2023-08-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_registeration_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='dates',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='location',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
    ]
