# Generated by Django 4.0.8 on 2025-09-02 10:07

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import forms.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_template_dates_template_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Only Sophomores with correct college email address are authorised.', regex='^[2][3][a-zA-Z]{3}\\d{3}@nith[.]ac[.]in$')]),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='resume',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/akshitpathania/iste/interviews/join.istenith.com/media')), upload_to='resumes/', validators=[forms.models.file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
    ]
