# Generated by Django 4.0.6 on 2022-08-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_rename_terms_condition_term_condition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social_Link',
        ),
        migrations.DeleteModel(
            name='Term_Condition',
        ),
        migrations.AddField(
            model_name='template',
            name='instagram',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='terms_conditions_content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='terms_conditions_title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='twitter',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
