# Generated by Django 4.0.6 on 2022-08-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_delete_social_link_delete_term_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('s_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terms_n_Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('tc_content', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='terms_conditions_content',
        ),
        migrations.RemoveField(
            model_name='template',
            name='terms_conditions_title',
        ),
    ]
