# Generated by Django 4.0.6 on 2022-08-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_social_links_terms_n_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='template',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='template',
            name='whatsapp',
        ),
    ]
