# Generated by Django 4.0.6 on 2022-08-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_remove_template_instagram_remove_template_twitter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Links',
            new_name='Social_Link',
        ),
        migrations.RenameModel(
            old_name='Terms_n_Conditions',
            new_name='Terms_n_Condition',
        ),
    ]
