# Generated by Django 4.0.6 on 2022-08-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_template_registration_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='Registration_Closed',
            new_name='Registeration_Closed',
        ),
    ]
