# Generated by Django 4.0.6 on 2022-08-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_rename_s_link_social_link_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social_link',
            options={'verbose_name': 'Social Link', 'verbose_name_plural': 'Social Links'},
        ),
        migrations.AlterModelOptions(
            name='terms_n_condition',
            options={'verbose_name': 'Terms & Condition', 'verbose_name_plural': 'Terms & Conditions'},
        ),
    ]
