# Generated by Django 4.0.6 on 2022-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_alter_registeration_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='terms_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
