# Generated by Django 4.0.6 on 2022-08-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_social_link_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='Registeration_Closed_Message',
            field=models.CharField(blank=True, max_length=10000000000, null=True),
        ),
    ]
