# Generated by Django 4.0.6 on 2022-08-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_social_link_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('rollno', models.CharField(blank=True, max_length=1000, null=True)),
                ('branch', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Selected Student',
                'verbose_name_plural': 'Selected Students',
            },
        ),
    ]
