# Generated by Django 4.0.6 on 2022-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_alter_registeration_terms_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='terms_confirmed',
            field=models.BooleanField(default=False, verbose_name='Terms Conditions'),
        ),
    ]
