# Generated by Django 4.0.6 on 2022-08-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='css_class_for_active_QNO',
            field=models.CharField(blank=True, default='c-faq--active', max_length=40, null=True),
        ),
    ]
