# Generated by Django 4.0.6 on 2022-08-11 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_faq_css_class_for_active_qno'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='success_message',
            field=models.CharField(max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Only sophomores with college email addresses are authorised.', regex='^[2][1][b][a-z]{2}\\d{3}@[nith.ac.in]*')]),
        ),
    ]
