# Generated by Django 4.0.6 on 2022-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_alter_registeration_terms_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_heading', models.CharField(blank=True, max_length=1000, null=True)),
                ('about_para', models.CharField(blank=True, max_length=10000, null=True)),
                ('download_para', models.CharField(blank=True, max_length=10000, null=True)),
                ('download_cv_pdf', models.FileField(blank=True, null=True, upload_to='sample_pdf/')),
                ('download_cv_doc', models.FileField(blank=True, null=True, upload_to='sample_doc/')),
                ('contact_para', models.CharField(blank=True, max_length=10000, null=True)),
                ('social_links_insta', models.CharField(blank=True, max_length=10000, null=True)),
                ('social_links_twitter', models.CharField(blank=True, max_length=10000, null=True)),
                ('social_links_whatsapp', models.CharField(blank=True, max_length=10000, null=True)),
                ('copyright_para', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registeration',
            name='terms_confirmed',
            field=models.BooleanField(default=False, verbose_name='Terms & Conditions'),
        ),
    ]
