# Generated by Django 4.0.6 on 2022-07-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_template_alter_registeration_terms_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='social_links_insta',
            new_name='intro_text',
        ),
        migrations.RemoveField(
            model_name='template',
            name='social_links_twitter',
        ),
        migrations.RemoveField(
            model_name='template',
            name='social_links_whatsapp',
        ),
    ]
