# Generated by Django 4.0.6 on 2022-08-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_alter_registeration_branch_alter_registeration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='terms_confirmed',
            field=models.BooleanField(verbose_name='Terms & Conditions'),
        ),
    ]
