version: '3'

services: 
  app:
    volumes:
      - media:/app/media/
      - database:/app/data/
    build: .
    ports:
      - "8081:8081"
    command: gunicorn --bind 0.0.0.0:8081 main.wsgi

volumes:
  media:
  database:

